name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git -c http.sslVerify=false submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Disable Wget SSL Verification
            run: echo "check_certificate = off" >> ~/.wgetrc
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: |
                mkdir -p buildroot/dl/zlib buildroot/dl/libzlib
                # Link direto para a versão 1.3.1 no GitHub do madler
                curl -L --insecure -o zlib-1.3.1.tar.xz https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.xz
                # Copia para as pastas onde o Buildroot procura
                cp zlib-1.3.1.tar.xz buildroot/dl/zlib/
                cp zlib-1.3.1.tar.xz buildroot/dl/libzlib/
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
